http_server:test.cc
	g++ -o http_server test1.cc -std=c++17 -g  -L../../source/http/httplib -lhttplib -I../../source/http -I../../source/tcp -I../../source/comm

PHONY:clean
clean: 
	rm -rf http_server